name: CustomRecipes
version: ${project.version}
api-version: 1.13
main: me.mehboss.recipe.Main
author: mehboss
description: An easy-to-use remastered custom recipe plugin!
softdepend: [PlaceholderAPI, AdvancedEnchantments, EcoEnchants, Eco, HavenBags, ItemsAdder, MythicMobs, MythicCrucible, LoneLibs, ProtocolLib, ExecutableItems, SCore, Oraxen, Nexo, MythicLib, MMOItems]
commands:
  crecipe:
    description: Displays the custom recipe help page.
    aliases: [crecipes, customrecipe, customrecipes, customr, cr]
  edititem:
    description: NBT Editor for items!
    aliases: [ei, edit]
    permission: crecipe.edititem
  recipes:
    description: Opens the recipe booklet!
    aliases: [recipe]
    permission: crecipe.book
permissions:
  crecipe.recipes:
    description: Allows the recipe command
    default: true
  crecipe.gui:
    description: Allows the gui command
    default: op
  crecipe.*:
    description: Grants all commands
    default: op
  crecipe.help:
    description: Allows the help command
    default: op
  crecipe.book:
    description: Allows the book command
    default: true