name: CustomRecipes
version: ${project.version}
api-version: 1.13
main: me.mehboss.recipe.Main
author: mehboss
description: An easy-to-use remastered custom recipe plugin!
softdepend: [PlaceholderAPI, AdvancedEnchantments, EcoEnchants, Eco, HavenBags, ItemsAdder, MythicMobs, LoneLibs, ProtocolLib, ExecutableItems, SCore, Oraxen, Nexo]
commands:
  crecipe:
    description: Displays the custom recipe help page.
    aliases: [crecipes, customrecipe, customrecipes, customr, cr]
    permissions:
      crecipe.*:
        default: op
  edititem:
    description: NBT Editor for items!
    aliases: [ei, edit]
    permissions:
      crecipe.*:
        default: op